/* eslint-disable */
// This file is automatically generated, do not edit!

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace UkSkyblurPost {
    /** Record containing a Skyblur post. */
    interface Record {
      $type: "uk.skyblur.post";
      /** Created date assigen by client */
      createdAt: string;
      /**
       * The post main contents. \
       * Maximum string length: 3000 \
       * Maximum grapheme length: 300
       */
      text: string;
      uri: At.Uri;
      /**
       * The post additional contents. \
       * Maximum string length: 100000 \
       * Maximum grapheme length: 10000
       */
      additional?: string;
    }
  }

  interface Records {
    "uk.skyblur.post": UkSkyblurPost.Record;
  }

  interface Queries {}

  interface Procedures {}
}

