/* eslint-disable */
// This file is automatically generated, do not edit!

type ObjectOmit<T, K extends keyof any> = Omit<T, K>;

/** handles type branding in objects */
export declare namespace Brand {
  /** Symbol used to brand objects, this does not actually exist in runtime */
  const Type: unique symbol;

  /** Get the intended `$type` field */
  type GetType<T extends { [Type]?: string }> = NonNullable<T[typeof Type]>;

  /** Creates a union of objects where it's discriminated by `$type` field. */
  type Union<T extends { [Type]?: string }> = T extends any
    ? T & { $type: GetType<T> }
    : never;

  /** Omits the type branding from object */
  type Omit<T extends { [Type]?: string }> = ObjectOmit<T, typeof Type>;
}

/** base AT Protocol schema types */
export declare namespace At {
  /**
   * represents a Content Identifier (CID) string
   */
  type Cid = string;

  /**
   * represents a Decentralized Identifier (DID).
   */
  type Did<Method extends string = string> = `did:${Method}:${string}`;

  /**
   * represents an account's handle, using domains as a human-friendly
   * identifier.
   */
  type Handle = `${string}.${string}`;

  /**
   * represents an account's identifier, either a {@link Did} or a
   * {@link Handle}
   */
  type Identifier = Did | Handle;

  /**
   * represents a Namespace Identifier (NSID)
   */
  type Nsid = `${string}.${string}.${string}`;

  /**
   * represents the unique key identifying a specific record within a
   * repository's collection. this is usually a {@link Tid}.
   */
  type RecordKey = string;

  /**
   * represents a Timestamp Identifier (TID)
   */
  type Tid = string;

  /**
   * represents a general AT Protocol URI, representing either an entire
   * repository, a specific collection within a repository, or a record.
   *
   * it allows using handles over DIDs, but this means that it won't be stable.
   */
  type ResourceUri =
    | `at://${Identifier}`
    | `at://${Identifier}/${Nsid}`
    | `at://${Identifier}/${Nsid}/${RecordKey}`;

  /**
   * represents a canonical AT Protocol URI for a specific record.
   *
   * this URI format uses the account's DID as the authority, ensuring that
   * the URI remains valid even as the account changes handles, uniquely
   * identifying a specific piece of record within AT Protocol.
   */
  type CanonicalResourceUri = `at://${Did}/${Nsid}/${RecordKey}`;

  /**
   * represents a generic URI
   */
  type GenericUri = `${string}:${string}`;

  /**
   * represents a Content Identifier (CID) reference
   */
  interface CidLink {
    $link: Cid;
  }

  /**
   * represents an object containing raw binary data encoded as a base64 string
   */
  interface Bytes {
    $bytes: string;
  }

  /**
   * represents a reference to a data blob
   */
  interface Blob<T extends string = string> {
    $type: "blob";
    mimeType: T;
    ref: {
      $link: string;
    };
    size: number;
  }
}
/** Decrypting the post by blob cid. */
export declare namespace UkSkyblurPostDecryptByCid {
  interface Params {}
  interface Input {
    cid: At.Cid;
    password: string;
    pds: At.GenericUri;
    repo: At.Did;
  }
  interface Output {
    text: string;
    additional?: string;
    message?: string;
  }
}

/** Encrypting the post. */
export declare namespace UkSkyblurPostEncrypt {
  interface Params {}
  interface Input {
    body: string;
    password: string;
  }
  interface Output {
    body: string;
    message?: string;
  }
}

/** Get Skyblur post. If the specified post is password-protected, you can retrieve the unlocked content by providing the password. */
export declare namespace UkSkyblurPostGetPost {
  interface Params {}
  interface Input {
    /** Skyblur post at-uri. It shoud be uk.skyblur.post collection. */
    uri: At.ResourceUri;
    /** If the specified uri is password-protected, please provide the password. If no password is specified, the non-protected content will be returned. */
    password?: string;
  }
  interface Output {
    text: string;
    additional?: string;
    message?: string;
  }
}

export declare namespace UkSkyblurPost {
  /** Record containing a Skyblur post. */
  interface Record {
    $type: "uk.skyblur.post";
    /** Created date assigned by client */
    createdAt: string;
    /**
     * The post main contents. Blurred text must be enclosed in brackets []. \
     * Maximum string length: 3000 \
     * Maximum grapheme length: 300
     */
    text: string;
    uri: At.ResourceUri;
    /**
     * For 'login', the post requires login to view (Bluesky account required). For 'password', the text only contains blurred text, and additional is always empty. The unblurred text and additional are included in the encryptBody. \
     * Maximum string length: 100 \
     * Maximum grapheme length: 10
     */
    visibility: "public" | "password" | "login";
    /**
     * The post additional contents. \
     * Maximum string length: 100000 \
     * Maximum grapheme length: 10000
     */
    additional?: string;
    /** Encrypted post body. It shoud be decrypted by the client with AES-256. */
    encryptBody?: At.Blob;
  }
}

export declare namespace UkSkyblurPreference {
  /** A declaration of a Skyblur account. */
  interface Record {
    $type: "uk.skyblur.preference";
    myPage: Brand.Union<UkSkyblurPreference.MyPage>;
  }
  interface MyPage {
    [Brand.Type]?: "uk.skyblur.preference#myPage";
    /** If this item is true, MyPage will be displayed. */
    isUseMyPage: boolean;
    /**
     * Define the description displayed on MyPage. \
     * Maximum string length: 10000 \
     * Maximum grapheme length: 100000
     */
    description?: string;
  }
}

export declare interface Records {
  "uk.skyblur.post": UkSkyblurPost.Record;
  "uk.skyblur.preference": UkSkyblurPreference.Record;
}

export declare interface Queries {}

export declare interface Procedures {
  "uk.skyblur.post.decryptByCid": {
    input: UkSkyblurPostDecryptByCid.Input;
    /** @deprecated */
    output: UkSkyblurPostDecryptByCid.Output;
    response: { json: UkSkyblurPostDecryptByCid.Output };
  };
  "uk.skyblur.post.encrypt": {
    input: UkSkyblurPostEncrypt.Input;
    /** @deprecated */
    output: UkSkyblurPostEncrypt.Output;
    response: { json: UkSkyblurPostEncrypt.Output };
  };
  "uk.skyblur.post.getPost": {
    input: UkSkyblurPostGetPost.Input;
    /** @deprecated */
    output: UkSkyblurPostGetPost.Output;
    response: { json: UkSkyblurPostGetPost.Output };
  };
}
