name: Release

on:
  push:
    branches:
      - main
      - preview

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy to Cloudflare
        run: |
          if [ "${{ github.ref }}" = "refs/heads/preview" ]; then
            npm run deploy:preview
          else
            npm run deploy
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
